version: '3.8'

services:
  starrupture:
    build: .
    container_name: starrupture
    restart: unless-stopped
    ports:
      - "7777:7777/udp"
      - "7777:7777/tcp"
      - "27015:27015/udp"
    volumes:
      - starrupture-data:/home/steam/starrupture
    environment:
      - SERVER_PORT=7777
      - QUERY_PORT=27015
      - MULTIHOME=0.0.0.0
      - UPDATE_ON_START=true
      - VALIDATE_ON_START=false
      # - ADDITIONAL_ARGS=

volumes:
  starrupture-data:
